[phases.build]
cmds = ['docker run -d --name redis-stack-server -p $REDISPORT:6379 redis/redis-stack-server:latest']
[start]
cmds = ["docker run -d --name redis-stack-server -p $REDISPORT:6379 redis/redis-stack-server:latest"]
